### PR TITLE
clean up sqlsoup fallout, minor issues, test failures

### PR DESCRIPTION
**Pull request by pabs3**
This pull request cleans up some fallout from the sqlsoup removal,
removes generated files from git in favour of rebuilding them,
cleans up minor Makefile/whitespace/spelling/grammar/other issues,
and fixes the test failures with Python 3.9 and 3.10.

The Python 3.9 fix is a bit of a hack and input is needed to fix it.

### CODE REVIEW

**Comment by ialbert** [comment]
Thanks for the detailed work. I will tag @micheles to bring this to his attention. 

It appears that the only backward incompatible change is that the `argparse` module in Python 3.10 replaces the wording in the autogenerated help from "optional arguments" to just "options". 

Plac now also applies the same wording but  retroactively for all Python versions.

I think the change is welcome and an appropriate fix.

When it comes to `plac_ext.py` I never used it myself, I feel that it contains code that is not directly relevant to how plac works (or why people pick plac versus other similar packages). Perhaps the best would be to remove plac_ext.py from the package itself.  Instead adding it as an example code that is not directly distributed with plac. That way we don't have to maintain that code.

**Comment by pabs3** [comment]
The second to last commit for Python 3.10 is the trivial options one.

The third to last commit for Python 3.9 is the problematic one. For
Python 3.9 argparse, when nargs is set to * the output is [foo ...]
instead of [foo [foo ...]]. I solved this by making a formatter class
(solely for the tests) that does the same as what Python 3.9 argparse
does, regardless of the Python version. It seemed wrong to have it just
for the tests rather than for all usage. I tried putting the fix into
the plac_ext.PlacFormatter class and using that in the tests, but then
the output had {} instead of the parameter names, seemingly because
PlacFormatter._metavar_formatter was deleting them. I couldn't figure
out how to get _metavar_formatter and _format_args in the same class.
I'm hoping that there is a better solution than separate classes.

I can't find anything that uses plac_ext, but there might be something,
maybe on PyPI. I'll leave it up to you to research that. I expect if
people try the unmaintained plac_ext.py they would file bugs about it.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I've added another commit to fix another issue I found when trying to
update the Debian package of plac. The plac_runner is ran using the
shebang rather than the same Python version as the doc/test_*.py files
are ran, which means that when testing multiple Python versions at
once, the wrong Python version is used for plac_runner, switching to
running plac_runner under sys.executable fixes that.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
@ialbert it looks like @micheles doesn't currently have time to review the changes.

I propose that you merge the commit series as-is (I've updated the commit message and PR status) and then make a new release, so that I can update the Debian python-plac package and other packages blocked by it.

Fixing the Python 3.9 issue for the tests is the main thing, the regular output can be synced with the Python 3.9 output at a later time when someone figures out how to do that.

For now I suggest keeping plac_ext. If you would like you could deprecate it in the next major release after this minor cleanup one and remove it in the major release after that.

**Comment by micheles** [comment]
Sorry, I have been really busy at work lately. I have reviewed the proposed changes and they are good, the PlacFormatter is a nice solution. Thank you for the big effort.

**Comment by ialbert** [comment]
thanks for all the effort on this @pabs3, much appreciated

**Comment by pabs3** [comment]
Thanks for merging!

I would appreciate a new release too so that I can update the Debian
package and have the tests work with Python 3.9/3.10 in Debian sid.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by ialbert** [comment]
I pushed out version 1.3.4 to PyPi

**Comment by pabs3** [comment]
Thanks, could you also push the tag to the GitHub repo?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by ialbert** [comment]
ok, tagged as v1.3.4

**Comment by pabs3** [comment]
Thanks!

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Pull request merged**
